### ISSUE TITLE
全体管理

### ISSUE THREAD

**Issue by komura-c** [01naoya01/ThreeCode#1]
## 実装手順
- [x] router.goでルーティング実装（01naoya01）#3 
- [x] index.html, room.htmlで画面表示実装（komura-c) #12
- [x] indexVue.jsで遷移, indexController.goで乱数生成実装（delta-EGG）#2
- [x] roomVue.jsボタンでルームURLコピー機能 #4
- [x] roomVue.js, room.html, router.goルームで反省抱負を書き込める（チャット機能）（Go+WebSocket非同期通信）#5
- [x] roomController.go、データベース設計考える #6 
- [x] 名前入力できるように、データベースに名前保存(何もなかったら匿名？) #6 
- [x] データベースにルーム作成（GoでMySQLにランダムなIDでRoom作成）#7 
- [x] その時に別の人がデザイン担当 #8 
- [x] ルームで反省抱負をデータベース連携（GoでMySQLにMessage作成）#9 
- [ ] （リアクション付けられるボタンかページ）#10
- [x] （誤投稿削除）#11

## 画面デザイン参考
[トップ画面](https://bosyu.me/)
[ルーム画面](https://trello.com/b/iuVU7Osk/%E3%81%BF%E3%82%93%E3%81%AA%E3%81%AE%E3%83%88%E3%83%AC%E3%83%AD%EF%BC%88trello%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%82%B3%E3%83%9F%E3%83%A5%E3%83%8B%E3%83%86%E3%82%A3)

## 事前イメージ
<img src="https://user-images.githubusercontent.com/37304826/103134790-14841900-46f7-11eb-9b9d-05185043b505.png" width="385" align="left">
<img src="https://user-images.githubusercontent.com/37304826/103134922-dfc49180-46f7-11eb-9554-2d9d04fba99c.png" width="385" align="left">
